### ISSUE TITLE
Rows are misaligned on mobile

### ISSUE THREAD

**Issue by jdmcd** [zurb/responsive-tables#48]
When shifting from desktop to mobile the rows of data in the table become misaligned, each row becoming gradually more shifted downwards.

Here is the CSS for the responsive table: 

```css
table td, table th { padding: 12px 10px; text-align: left; }

/* Mobile */
@media only screen and (max-width: 767px) {
	
	table.responsive { margin-bottom: 0; }
	
	.pinned { position: absolute; left: 0; top: 0; background: #fff; width: 35%; overflow: hidden; overflow-x: scroll; border-right: 1px solid #ccc; border-left: 1px solid #ccc; }
	.pinned table { border-right: none; border-left: none; width: 100%; }
	.pinned table th, .pinned table td { white-space: nowrap; }
	.pinned td:last-child { border-bottom: 0; }
	
	div.table-wrapper { position: relative; margin-bottom: 20px; overflow: hidden; border-right: 1px solid #ccc; }
	div.table-wrapper div.scrollable { margin-left: 35%; }
	div.table-wrapper div.scrollable { overflow: scroll; overflow-y: hidden; }	
	
	table.responsive td, table.responsive th { position: relative; white-space: nowrap; overflow: hidden; }
	table.responsive th:first-child, table.responsive td:first-child, table.responsive td:first-child, table.responsive.pinned td { display: none; }
}
```

How can I fix this? It's such a prevalent bug that the last row can't even be read. 

Huge fan of the library, it's worked great otherwise. Thanks so much in advance!
